# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2837032581a42213895621f0adc607d7f54736bec0b6995260de46b5c176ed4f9d792493ea2cdad347e68e1a9cc77caff303a914e85c8f59cb6dcfeaf5fd549a

test:
  secret_key_base: ff8c03ab09ef913d9605d63fd7f26f5697896ec5bc99a5d6b77e9acd2f4779109a46212c85f2cfbc1491a85fef95ab5ab13b99eb5edb42a8534679602ac9ebd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
